schema:
    file: ./schema.yaml
    format: yaml

input:
    files: ./i18n/**.yaml
    format: yaml
    fallback: ./i18n/en.yaml

output:
    dir: ./dist
    format: json
    stringFormat: compact-parts

hooks:
    files:
        - ./hooks.js
