keys:
    - name: HelloThere
      description: Represents a "Hello!" message.

    - name: HowAreYou
      description: Represents a "How are you?" message.

    - name: ThankYou
      description: Represents a "Thank you!" message.

    - name: HelloX
      description: Say "Hello" to an user.
      parameters: [user]
